version: '3'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    image: docfook55/my-backend_image:1.0
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    image: docfook55/my-frontend_image:1.0
